### ISSUE TITLE
It cannot find sources inside other sources

### ISSUE THREAD

**Issue by nbauma109** [aconrad/pycobertura#182]
The script complained that it couldn't find a source file:

`pycobertura.filesystem.FileSystem.FileNotFound: sources_new\com/mycompany/mypackage/SomeEnum.java`

It turned out that Enum was declared in another source file:

`com/mycompany/mypackage/SomeClass.java`

```java
package com.mycompany.mypackage;

enum SomeEnum {

}

public class SomeClass {

}
```

Unfortunately, this blocks the whole process!

**Comment by aconrad** [comment]
Can you provide more information about your setup?

* What are the commands you are providing to pycobertura?
* Can you show a relevant snippet of the coverage file?
* Provide a snippet of your directory tree to understand the layout of your source code

**Comment by nbauma109** [comment]
I'm currently working on a side project [source-extractor](https://github.com/nbauma109/source-extractor) to prepare the files to be processed by pycobertura. It's normal that pycobertura doesn't find the class/object definitions that are not defined in their own files, that would require parsing java and scala and I believe it's beyond the scope of pycobertura.

**Comment by aconrad** [comment]
I'm not sure I understand. But if your project generates cobertura reports when you run your tests, then pycobertura can parse those reports. Accessing the Java source files of your project is necessary if you want pycobertura to generate, say, an HTML report that highlights which source lines are covered or uncovered. Otherwise it's optional but you get less features out of pycobertura.

**Comment by nbauma109** [comment]
Yes, I want to generate this html report with the highlights. Unfortunately, this "file not found" error blocks the whole process.

**Comment by nbauma109** [comment]
Good news. I managed to generate the html report thanks to the source extractor.
